// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SafeRoad.Infrastructure.Migrations
{
    [DbContext(typeof(SafeRoadDbContext))]
    [Migration("20260227142454_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeRoad.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This pothole has been here for weeks, really dangerous!",
                            CreatedAt = new DateTime(2025, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 2,
                            Content = "Municipality team is on the way to fix this.",
                            CreatedAt = new DateTime(2025, 1, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            Content = "I almost had an accident because of this traffic light.",
                            CreatedAt = new DateTime(2025, 1, 13, 8, 30, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            Content = "The flooding is really bad, avoid this road!",
                            CreatedAt = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep pothole causing vehicle damage near the city center.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.7133 36.8969)"),
                            MunicipalityId = 1,
                            ReporterUserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            Status = "Pending",
                            Title = "Large Pothole on Atatürk Boulevard"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Traffic light has been non-functional for 3 days.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.7 36.88)"),
                            MunicipalityId = 3,
                            ReporterUserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            Status = "Verified",
                            Title = "Broken Traffic Light at Işıklar Street"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Street is flooded after heavy rain, making it impassable.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.65 36.87)"),
                            MunicipalityId = 4,
                            ReporterUserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            Status = "Pending",
                            Title = "Flooding on Konyaaltı Beach Road"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000004"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Speed limit sign is missing after an accident.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.99 36.544)"),
                            MunicipalityId = 5,
                            ReporterUserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            Status = "Resolved",
                            Title = "Missing Road Sign on Alanya Highway"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000005"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Long crack across the road causing safety concerns.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.73 37.01)"),
                            MunicipalityId = 2,
                            ReporterUserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            Status = "Pending",
                            Title = "Road Crack on Kepez Industrial Zone"
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.IncidentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("IncidentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pothole"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Road Crack"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Broken Traffic Light"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Missing Road Sign"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flooding"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Road Accident"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Obstacle on Road"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Broken Guardrail"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Damaged Sidewalk"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Street Light Out"
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.IncidentPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentPhotos");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.JourneyIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Feedback")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("JourneyId");

                    b.ToTable("JourneyIncidents");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Polygon>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Antalya Metropolitan Municipality"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kepez Municipality"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Muratpaşa Municipality"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Konyaaltı Municipality"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alanya Municipality"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Manavgat Municipality"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Serik Municipality"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Döşemealtı Municipality"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Aksu Municipality"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gazipaşa Municipality"
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Municipality"
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@saferoad.com",
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$5J9R2E3V6vFmK1hL4nQ7aeRSLZJk3C4BXB5oU6WpYgfUtwK0HbYpy",
                            Status = "Active",
                            TrustScore = 100
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "moderator@antalya.bel.tr",
                            FullName = "Antalya Metro Moderator",
                            PasswordHash = "$2a$11$5J9R2E3V6vFmK1hL4nQ7aePwuXiLmnZ1HkD8vVA0QqGe3J7c2sMqi",
                            Status = "Active",
                            TrustScore = 100
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@gmail.com",
                            FullName = "John Doe",
                            PasswordHash = "$2a$11$5J9R2E3V6vFmK1hL4nQ7aeT9kN2rM8b3GsDf5YiW0ExH6jR4lCvOu",
                            Status = "Active",
                            TrustScore = 100
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@gmail.com",
                            FullName = "Jane Smith",
                            PasswordHash = "$2a$11$5J9R2E3V6vFmK1hL4nQ7aeT9kN2rM8b3GsDf5YiW0ExH6jR4lCvOu",
                            Status = "Active",
                            TrustScore = 100
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "officer@kepez.bel.tr",
                            FullName = "Kepez Municipality Officer",
                            PasswordHash = "$2a$11$5J9R2E3V6vFmK1hL4nQ7aeZVd4gCpO7RuFn9XbQ1ImK5tW2yEoMns",
                            Status = "Active",
                            TrustScore = 100
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.UserJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LineString>("RoutePath")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserJourneys");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            RoleId = 3
                        },
                        new
                        {
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            RoleId = 2
                        },
                        new
                        {
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000005"),
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("Verifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            IsPositive = true,
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            IsPositive = true,
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            IsPositive = true,
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            IsPositive = true,
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = new Guid("b2b2b2b2-0000-0000-0000-000000000004"),
                            IsPositive = false,
                            UserId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.WatchedArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Area")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RadiusInMeters")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WatchedAreas");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Comment", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.DeviceToken", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Incident", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.IncidentCategory", "Category")
                        .WithMany("Incidents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoad.Core.Entities.Municipality", "Municipality")
                        .WithMany("Incidents")
                        .HasForeignKey("MunicipalityId");

                    b.HasOne("SafeRoad.Core.Entities.User", "Reporter")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Municipality");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.IncidentPhoto", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.Incident", "Incident")
                        .WithMany("Photos")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.JourneyIncident", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.Incident", "Incident")
                        .WithMany("JourneyIncidents")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoad.Core.Entities.UserJourney", "Journey")
                        .WithMany("JourneyIncidents")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.UserJourney", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("UserJourneys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.UserRole", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Verification", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.Incident", "Incident")
                        .WithMany("Verifications")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("Verifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.WatchedArea", b =>
                {
                    b.HasOne("SafeRoad.Core.Entities.User", "User")
                        .WithMany("WatchedAreas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Incident", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("JourneyIncidents");

                    b.Navigation("Photos");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.IncidentCategory", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Municipality", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DeviceTokens");

                    b.Navigation("ReportedIncidents");

                    b.Navigation("UserJourneys");

                    b.Navigation("UserRoles");

                    b.Navigation("Verifications");

                    b.Navigation("WatchedAreas");
                });

            modelBuilder.Entity("SafeRoad.Core.Entities.UserJourney", b =>
                {
                    b.Navigation("JourneyIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
